# Generated by Django 4.2.2 on 2023-07-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, null=True)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'searchbox',
            },
        ),
    ]
