# Generated by Django 4.2.2 on 2023-08-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore_payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Cancel', 'Cancel')], max_length=20),
        ),
    ]
